name: Sync Fork and Build Docker Image
on: 
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  
jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/weaviate/Verba.git
          git fetch upstream

      - name: Sync fork
        id: sync
        run: |
          git checkout main
          git merge origin/main
          UPSTREAM_CHANGES=$(git rev-list --count HEAD..upstream/main)
          if [ "$UPSTREAM_CHANGES" -gt 0 ]; then
            git merge --no-edit upstream/main || (echo "Merge conflict detected. Please resolve manually." && exit 1)
            git push origin main || (echo "Failed to push changes. Please check your permissions." && exit 1)
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to sync"
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER_NAME }}/verba:latest
            ${{ secrets.DOCKER_HUB_USER_NAME }}/verba:${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/image.tar

      - name: Check Docker Hub for image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USER_NAME }}/verba:latest
          if [ $? -eq 0 ]; then
            echo "Image successfully pushed and pulled from Docker Hub"
          else
            echo "Failed to pull image from Docker Hub. It may not have been pushed successfully."
            exit 1
          fi
